### ISSUE TITLE
Model checkpoints?

### ISSUE THREAD

**Issue by yogeshchandrasekharuni** [megvii-research/MM2022-ViCoPerceptualHeadGeneration#2]
Hi, do you plan on releasing your trained model's weights? It would be cool if we could skip the training process again.

**Comment by hzwer** [comment]
Hello, this work is far from an actual head synthesis system. This work is mainly to help our interns get started in related fields. 
We sincerely recommend some more complete repo to you: 
https://yudongguo.github.io/ADNeRF/
https://github.com/yiranran/Audio-driven-TalkingFace-HeadPose

**Comment by yogeshchandrasekharuni** [comment]
Thank you for replying. I am looking for a talking-head generation model that uses just a target person's portrait image and an audio file to generate the final video. Any suggestions?

**Comment by hzwer** [comment]
Sounds like this happens to be the setting for the Vico challenge. 
You may refer to some gan-based methods. https://michaildoukas.github.io/HeadGAN/

**Comment by yogeshchandrasekharuni** [comment]
This helps, thank you for your suggestion!
