### ISSUE TITLE
Is there no listener_generator?

### ISSUE THREAD

**Issue by nuo1wang** [megvii-research/MM2022-ViCoPerceptualHeadGeneration#4]
I've notice there seems to be no modifications to `listenr_generator.py` in vico baseline method. Does it mean that this method has the same listener training pipeline as the original baseline? And if I already have the pretrained weights of the baseline method, I can use it directly in this code, right?

**Comment by P2Oileen** [comment]
> this method has the same listener training pipeline as the original baseline

Yes 😀
