### ISSUE TITLE
inference.py outputs ground truth video rather than the generated one.

### ISSUE THREAD

**Issue by nuo1wang** [megvii-research/MM2022-ViCoPerceptualHeadGeneration#5]
I've notice that `vico_challenge_baseline/PIRender/inference.py` outputs the ground truth video rather than the generated one. It should be a problem with `write2video()` function. After I replace this function with the original one in vico baseline, the output seems to be correct. Please consider fixing this.

**Comment by P2Oileen** [comment]
Thank you for kindly remind! @hzwer Please check this
